#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: fabric-sdk-node
  description: Hyperledger Fabric SDK for Node https://wiki.hyperledger.org/display/fabric
  homepage: https://hyperledger.github.io/fabric-sdk-node/
  default_branch: master
  has_downloads: true
  has_issues: false
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
