name: Test

on:
  workflow_call:
    inputs:
      checkout-ref:
        default: ''
        required: false
        type: string

env:
  SOFTHSM2_CONF: ${{ github.workspace }}/test/fixtures/hsm/softhsm2.conf

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 10
          - 12
          - 14
          - 16

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout-ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install SoftHSM
        run: |
          sudo apt-get install softhsm2
          softhsm2-util --init-token --slot 0 --label "My token 1" --pin 98765432 --so-pin 98765432

      - name: npm install
        run: npm install

      - name: Run tests
        run: npm test
